version: '3'
services:
  crow:
    build: ./crow
    container_name: cpp-comparison-crow
    image: cpp-comparison-crow
    command: /usr/src/crow/build/cpp_comparison_crow
    ports: ["18001:18001"]

  cpprestsdk:
    build: ./cpprestsdk
    container_name: cpp-comparison-cpprestsdk
    image: cpp-comparison-cpprestsdk
    command: /usr/src/cpprestsdk/build/cpp_comparison_cpprestsdk
    ports: ["18002:18002"]

  simple_web_server:
    build:
      context: ./
      dockerfile: ./simple_web_server/Dockerfile
    container_name: cpp-comparison-simple-web-server
    image: cpp-comparison-simple-web-server
    command: /usr/src/simple_web_server/build/cpp_comparison_simple_web_server
    ports: ["18003:18003"]

  pistache:
    build:
      context: ./
      dockerfile: ./pistache/Dockerfile
    container_name: cpp-comparison-pistache
    image: cpp-comparison-pistache
    command: /usr/src/pistache/build/cpp_comparison_pistache
    ports: ["18004:18004"]

  restbed:
    build:
      context: ./
      dockerfile: ./restbed/Dockerfile
    container_name: cpp-comparison-restbed
    image: cpp-comparison-restbed
    command: /usr/src/restbed/build/cpp_comparison_restbed
    ports: ["18005:18005"]
